apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tribe
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api 