version: "2"

run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/api/handlers/activity_test\.go
      linters:
        - typecheck
  
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

output:
  print-issued-line: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US 