# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  misspell:
    locale: US 

issues:
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv|.*Rollback). is not checked"

  exclude-use-default: false
  max-per-linter: 0
  max-same: 0

run:
  go: "1.24"
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly 