run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US 