# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    
  settings:
    govet:
      enable:
        - shadow
    gofmt:
      simplify: true
    misspell:
      locale: US 

  exclusions:
    rules:
      - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv|.*Rollback). is not checked"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  go: "1.24"
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly 