# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US 

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/api/handlers/activity_test\.go
      linters:
        - typecheck
  
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true

run:
  go: "1.21"
  timeout: 5m
  skip-dirs:
    - vendor 