# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"

# Database Configuration
database:
  host: localhost
  port: 5432
  name: rlship_tools
  user: postgres
  password: postgres
  sslmode: disable

# Redis Configuration
redis:
  host: localhost
  port: 6379
  db: 0

# Firebase Configuration
firebase:
  project_id: test-project
  credentials_file: /tmp/firebase-credentials.json

# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 24h # 24 hours

# Storage Configuration
storage:
  bucket: your-storage-bucket 