# Server Configuration
port: 8080

# Database Configuration
database:
  host: localhost
  port: 5432
  name: rlship
  user: postgres
  password: postgres

# Redis Configuration
redis:
  host: localhost
  port: 6379
  db: 0

# Firebase Configuration
firebase:
  project_id: your-project-id
  storage_bucket: your-project-id.appspot.com

# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 24h # 24 hours

# Storage Configuration
storage:
  bucket: your-storage-bucket 