-- Remove constraints
ALTER TABLE list_items DROP CONSTRAINT IF EXISTS location_data_complete;
ALTER TABLE list_items DROP CONSTRAINT IF EXISTS seasonal_dates_complete;
ALTER TABLE tribe_members DROP CONSTRAINT IF EXISTS guest_membership_expires;

-- Remove default values
ALTER TABLE list_items ALTER COLUMN available DROP DEFAULT;
ALTER TABLE list_items ALTER COLUMN seasonal DROP DEFAULT;
ALTER TABLE list_items ALTER COLUMN chosen_count DROP DEFAULT;
ALTER TABLE list_items ALTER COLUMN use_count DROP DEFAULT;
ALTER TABLE lists ALTER COLUMN default_weight DROP DEFAULT;

-- Make fields nullable again
ALTER TABLE activities ALTER COLUMN type DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN name DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN description DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN visibility DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE lists ALTER COLUMN type DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN name DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN description DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN visibility DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN sync_status DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN default_weight DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE lists ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE list_items ALTER COLUMN name DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN description DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN weight DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN available DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN seasonal DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN chosen_count DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN use_count DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE list_items ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE tribes ALTER COLUMN name DROP NOT NULL;
ALTER TABLE tribes ALTER COLUMN type DROP NOT NULL;
ALTER TABLE tribes ALTER COLUMN description DROP NOT NULL;
ALTER TABLE tribes ALTER COLUMN visibility DROP NOT NULL;
ALTER TABLE tribes ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE tribes ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE tribe_members ALTER COLUMN membership_type DROP NOT NULL;
ALTER TABLE tribe_members ALTER COLUMN display_name DROP NOT NULL;
ALTER TABLE tribe_members ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE tribe_members ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE users ALTER COLUMN firebase_uid DROP NOT NULL;
ALTER TABLE users ALTER COLUMN provider DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN name DROP NOT NULL;
ALTER TABLE users ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE users ALTER COLUMN updated_at DROP NOT NULL; 